site_name: loadx
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            members_order: source

nav:
  - Home: index.md
  - API Reference:
      - Strategies:
          - SCD2 (History):
              - Loader: api/scd2/loader.md
              - Config: api/scd2/config.md
              - Transforms: api/scd2/transforms.md
      - Exceptions: api/exceptions.md
