site_name: loadx
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            members_order: source

nav:
  - Home: index.md
  - API Reference:
      - Strategies:
          - SCD2 (History):
              - Loader: api/scd2/loader.md
              - Config: api/scd2/config.md
              - Processor: api/scd2/processor.md
              - Validator: api/scd2/validator.md
              - Services:
                  - DataService: api/scd2/services/data_service.md
                  - HashService: api/scd2/services/hash_service.md
                  - DateService: api/scd2/services/date_service.md
      - Exceptions: api/exceptions.md
