FROM mcr.microsoft.com/devcontainers/python:1-3.8-bullseye

# Install necessary packages
RUN apt-get update && apt-get install -y wget openjdk-11-jre
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
